### PR TITLE
Fix getRecord and getRelCatEntry

### PR DESCRIPTION
**Pull request by SaintNerevar**
getRecord is checking for the wrong constant and getRelCatEntry is not checking if getRecord succeeds.

### CODE REVIEW

**Review by jessiyajoy — APPROVED** [review]

**Review by jessiyajoy — COMMENTED** [review]
This looks good. Also won't the same correction be applicable in getAttrCatEntry as well?
lines:
- 809
- 840

**Review by jessiyajoy — COMMENTED** [review]
And also the same correction needs to be done for the 3 setter functions (1 for relcat and 2 for attrcat)

**Review by jessiyajoy — COMMENTED** [review]
Found one more similar place that will need changes **(XFS_Interface/OpenRelTable.cpp)** :
```cpp
int OpenRelTable::openRelation(char relationName[ATTR_SIZE]) {
	Attribute relationCatalog[6];

	/* check if relation exists
	 *      for this check each entry in relation catalog
	 */
	int i;
	for (i = 0; i < SLOTMAP_SIZE_RELCAT_ATTRCAT; i++) {
		getRecord(relationCatalog, 4, i);
		if (strcmp(relationCatalog[0].sval, relationName) == 0) {
			break;
		}
	}
.........
}
```

**Comment by SaintNerevar** [comment]
Okay! All done

**Pull request merged**
